# Generated by Django 4.1.4 on 2022-12-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(editable=False, max_length=99)),
                ('middle_name', models.CharField(blank=True, editable=False, max_length=99, null=True)),
                ('last_name', models.CharField(editable=False, max_length=99)),
                ('phone_number', models.CharField(editable=False, max_length=99)),
                ('email_address', models.EmailField(blank=True, editable=False, max_length=99, null=True)),
                ('amount', models.IntegerField(editable=False)),
                ('currency', models.CharField(editable=False, max_length=3)),
                ('description', models.TextField(editable=False, max_length=200)),
                ('country_code', models.CharField(blank=True, editable=False, max_length=3, null=True)),
                ('zip_code', models.CharField(blank=True, editable=False, max_length=99, null=True)),
                ('notification_id', models.CharField(blank=True, editable=False, max_length=99, null=True)),
                ('payment_status', models.BooleanField(blank=True, default=False, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Billing Info',
            },
        ),
    ]
