# Generated by Django 4.1.4 on 2022-12-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=99)),
                ('email', models.EmailField(editable=False, max_length=254)),
                ('phone_number', models.CharField(editable=False, max_length=99)),
                ('website', models.CharField(editable=False, max_length=99)),
                ('subject', models.CharField(editable=False, max_length=99)),
                ('message', models.TextField(editable=False, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
