# Generated by Django 4.1.4 on 2022-12-20 12:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('author', models.CharField(max_length=99)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=99)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Customer Billing Info',
            },
        ),
    ]
