# Generated by Django 4.1.4 on 2022-12-20 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=90, unique=True)),
                ('product_price', models.IntegerField()),
                ('product_sub_category', models.CharField(max_length=90)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_color', models.CharField(blank=True, max_length=90, null=True)),
                ('product_size', models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('XS-S', 'XS-S'), ('S', 'S'), ('M', 'M'), ('M-L', 'M-L'), ('L', 'L'), ('XL', 'XL')], max_length=90, null=True)),
                ('product_rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=90)),
                ('is_inOffer', models.BooleanField(default=False, verbose_name='In Offer')),
                ('images', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_inStock', models.BooleanField(default=True, verbose_name='In Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the product active?')),
                ('product_category', models.ForeignKey(max_length=90, on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
